# Generated by Django 4.2.11 on 2025-04-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreplenishment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreplenishment',
            old_name='default_value',
            new_name='defaultVvalue',
        ),
        migrations.RenameField(
            model_name='productreplenishment',
            old_name='provider_email',
            new_name='providerEmail',
        ),
        migrations.RenameField(
            model_name='productreplenishment',
            old_name='provider_name',
            new_name='providerName',
        ),
        migrations.RenameField(
            model_name='productreplenishment',
            old_name='provider_number',
            new_name='providerNumber',
        ),
    ]
