# Generated by Django 4.2.11 on 2025-04-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreplenishment',
            old_name='defaultVvalue',
            new_name='defaultValue',
        ),
    ]
