# Generated by Django 4.2.11 on 2025-04-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_defaultvvalue_productreplenishment_defaultvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreplenishment',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
